SELECT IL.NAME, I.SUMMARY, I.DESCRIPTION
FROM ISSUESLISTS IL JOIN  ISSUE I  ON IL.ID = I.ISSUES_LIST
ORDER BY IL.NAME;

SELECT U.FIRSTNAME, U.LASTNAME, I.DESCRIPTION, I.SUMMARY
FROM USERS U
         JOIN ISSUE I ON U.ID = I.USER_ID_ASSIGNEDTO;

SELECT U.FIRSTNAME, U.LASTNAME, COUNT(I.ID) AS EXERCISE_NUMBER
FROM USERS U
         LEFT JOIN ISSUE I ON U.ID = I.USER_ID_ASSIGNEDTO
GROUP BY U.FIRSTNAME, U.LASTNAME;

COMMIT;